// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRyg5kJ6qCqANau_HqvTMOQH7B9nhg9Lg',
    appId: '1:593573993806:web:b7be1ff8895a08fdbf121f',
    messagingSenderId: '593573993806',
    projectId: 'movie-review-fd36b',
    authDomain: 'movie-review-fd36b.firebaseapp.com',
    storageBucket: 'movie-review-fd36b.firebasestorage.app',
    measurementId: 'G-Y1CZWEJXVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPO4V66SK1GsIaG2YuSSpI55AZARws58',
    appId: '1:593573993806:android:eb02e06a0639df02bf121f',
    messagingSenderId: '593573993806',
    projectId: 'movie-review-fd36b',
    storageBucket: 'movie-review-fd36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkzD4qCug24T3WN4o2dF8jCX27OtqBHLk',
    appId: '1:593573993806:ios:aa7bf467dbcd6939bf121f',
    messagingSenderId: '593573993806',
    projectId: 'movie-review-fd36b',
    storageBucket: 'movie-review-fd36b.firebasestorage.app',
    iosBundleId: 'com.example.movieReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkzD4qCug24T3WN4o2dF8jCX27OtqBHLk',
    appId: '1:593573993806:ios:aa7bf467dbcd6939bf121f',
    messagingSenderId: '593573993806',
    projectId: 'movie-review-fd36b',
    storageBucket: 'movie-review-fd36b.firebasestorage.app',
    iosBundleId: 'com.example.movieReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRyg5kJ6qCqANau_HqvTMOQH7B9nhg9Lg',
    appId: '1:593573993806:web:10954b20f7d9a9efbf121f',
    messagingSenderId: '593573993806',
    projectId: 'movie-review-fd36b',
    authDomain: 'movie-review-fd36b.firebaseapp.com',
    storageBucket: 'movie-review-fd36b.firebasestorage.app',
    measurementId: 'G-XFZ55GDKYH',
  );
}
